aboutUs/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'aboutUs'

urlpatterns = [
    path('', views.AboutUs, name='aboutUs'),
    path('showText/', views.showText, name='showText'),
    path('aboutUs/tampilkan-kritik/', views.tampilkan_kritik, name='tampilkanKritik'),

]

educovid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rs_rujukan/', include('rs_rujukan.urls', namespace='rs_rujukan')),
    path('', include('covid_count.urls', namespace='covid_count')),
    path('edukasi/', include('edukasi.urls', namespace='edukasi')),
    path('screening_tests/', include('screening_tests.urls', namespace='screening_tests')),
    path('aboutUs/', include('aboutUs.urls', namespace='aboutUs')),
    path('register/', include('register.urls', namespace='register'))
]

rs_rujukan/urls.py
from django.contrib import admin
from django.urls import path
from rs_rujukan import views

app_name = "rs_rujukan"

urlpatterns = [
   	path('', views.index, name='index'),
   	# path('data_rs/', views.data_rs, name='data_rs'),
   	path('rs_api/', views.rs_api, name='rs_api'),
   	path('add_rs/', views.add_rs, name='add_rs'),
]

rs_rujukan/models.py
from django.db import models

# Create your models here.
class RumahSakit(models.Model):
	nama = models.CharField(max_length=50, blank=False)
	provinsi = models.CharField(max_length=30, blank=False)
	telepon = models.CharField(max_length=15, blank=False)
	alamat = models.CharField(max_length=200, blank=False)

	class Meta:
		ordering = ['provinsi', 'nama']

	def __str__(self):
		return self.nama

rs_rujukan/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .models import RumahSakit
from register.forms import LoginForm
from django.contrib.auth.models import User
from register.models import Register
from django.http import JsonResponse, HttpResponse
from django.contrib.auth import authenticate, login
from django.core.serializers import serialize
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import requests
import json

# Create your views here.
def index(request):
	response = {}
	data = RumahSakit.objects.all()
	response = {'data':data}
	
	# Navbar Login Section
	uname: str = request.user.username	
	response["greeting"] = "Hello, " + (uname if len(uname) <= 10 else (uname[0:5] + "..."))
	response["login_form"] = LoginForm

	if (request.user.is_authenticated):
		user = get_object_or_404(User, username=request.user.username)
		profile = get_object_or_404(Register, user=user)
		response['provinsi'] = profile.province

	return render(request, 'rs_rujukan/rs_rujukan.html', response)

def rs_api(request):
	data = RumahSakit.objects.all()
	data_list = serialize('json', data)
	return HttpResponse(data_list, content_type="text/json-comment-filtered")\

def add_rs(request):
	if request.user.is_superuser :
		response = {}
		if (request.method == 'POST'):
			nama = request.POST.get('nama')
			provinsi = request.POST.get('provinsi')
			alamat = request.POST.get('alamat')
			telepon = request.POST.get('telepon')
			RumahSakit.objects.create(nama=nama, provinsi=provinsi, telepon=telepon, alamat=alamat)

		return render(request, 'rs_rujukan/add_rs.html', response)

	messages.error(request, "❌ Akses Ditolak ❌")
	return redirect('/rs_rujukan')

# def data_rs(request):
# 	url = "https://services5.arcgis.com/VS6HdKS0VfIhv8Ct/arcgis/rest/services/RS_Rujukan_Update_May_2020/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json"
# 	response = requests.get(url)
# 	data = response.json()
# 	return JsonResponse(data, safe = False)

rs_rujukan/templates/rs_rujukan/add_rs.html
{% extends 'base.html' %}
{% load static %}

{% block additional-styles %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.bootstrap.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'rs_rujukan.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'add_rs.css' %}">
	<title>EDUCOVID - RS Rujukan</title>
{% endblock %}
{% block content %}
<div class="container pagelist justify-content-center my-5">
	<div class="alert alert-success" role="alert" id="sukses" style="display: none;">
	  ✅ <strong>Berhasil</strong> Menambahkan Data Rumah Sakit! 
	</div>

	<a href="{% url 'rs_rujukan:index' %}"><button class="btn btn-primary mt-2">Back</button></a>
	
	<h1 class="text-center mt-3 mb-5"><bold>FORM PENAMBAHAN DATA RUMAH SAKIT</bold></h1>
	<br>
	<form method='POST' id="rs_form">
		{% csrf_token %}

		<label>Nama Rumah Sakit</label>
		<input type="text" class="form-control" id="nama" placeholder="Rumah Sakit.." required>
		<br>
		<label>Provinsi</label>
		<input type="text" class="form-control" id="provinsi" placeholder="Provinsi..." required>
		<br>
		<label>Alamat</label>
		<input type="text" class="form-control" id="alamat" placeholder="Alamat..." required>
		<br>
		<label>Nomor Telepon</label>
		<input type="text" class="form-control" id="telepon" placeholder="021-..." required>
		<br>
		<button type="submit" class="btn btn-primary mt-5">Submit</button>
	</form>

</div>


<script>
	// $("#sukses").hide()
	$("#rs_form").submit(function (e){
		e.preventDefault();

		$.ajax({
			type:'POST',
			url:'/rs_rujukan/add_rs/',
			data:{
				nama:$("#nama").val(),
				alamat:$("#alamat").val(),
				telepon:$("#telepon").val(),
				provinsi:$("#provinsi").val(),
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
            	action: 'post',
			},
			success: function(data){
	        	$("#sukses").show()
	        	setTimeout(function(){ $("#sukses").fadeOut(); }, 5000); 
	        	$("#rs_form").trigger("reset")
	        }
		})
	})
</script>
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
<!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script> -->
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script> -->
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/responsive.bootstrap.min.js"></script>
{% endblock %}

rs_rujukan/templates/rs_rujukan/rs_rujukan.html
{% extends 'base.html' %}
{% load static %}

{% block additional-styles %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.bootstrap.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'rs_rujukan.css' %}">
	<script type="text/javascript" src="{% static 'rs_rujukan.js' %}"></script>
	<title>EDUCOVID - RS Rujukan</title>
{% endblock %}
{% block content %}
<div class="container-fluid">
	{% for message in messages %}
 		{% if message.tags == 'success' %}
		<div class="alert alert-success">
		    <a class="close" data-dismiss="alert">❎</a>
		   	{{message}}
		</div>
		{% else %}
		<div class="alert alert-danger">
		    <a class="close" data-dismiss="alert">❌</a>
		   	{{message}}
		</div>
		{% endif %}
	{% endfor %}

	<h1 class="text-center m-5 judul">Daftar Rumah Sakit Rujukan</h1>
	
	<div class="bar d-flex text-center">
		<h5 class='rs_terdekat text-center'>🏥 RS Rujukan Provinsi Terdekat 🏥
			<br>
			<br>

			{% if request.user.is_authenticated %}
				<button id="find" class="btn btn-info btn-sm"><h5 style="margin:2px;">Cari 🔎</h5></button>
			{% else %}
				<p><small  class="text-muted">Harap login untuk menggunakan fitur ini</small></p>
			{% endif %}
			<div id="answer"></div>
			<button class="btn btn-danger btn-sm mt-3" id="call"><h5 style="margin:2px;">📞 Panggil Sekarang</h5>
			</button>
			<a href="#" id="link"></a>
		</h5>
	</div>
	

    <table class="table table-striped" id="mytable">
    	<thead class="thead table-bordered">
	        <tr>
	            <th style="width: 30%">Nama Rumah Sakit</th>
	            <th style="width: 15%">Provinsi</th>
	            <th>Alamat</th>
	            <th style="width: 12%">Telepon</th>
	        </tr>
	    </thead>
    	<tbody class="tbody table-bordered">
    	</tbody>
    </table>
    <br>
    <br>
    {% if request.user.is_superuser %}
	    <a  href="{% url 'rs_rujukan:add_rs' %}">
	    <button class="btn btn-primary my-5">Tambah Data Rumah Sakit</button></a>
	{% endif %}
</div>

<script>
	$("#call").hide();
	$("#find").click(function() {
		var nama_rs = ""
		$.ajax({
			url : "/rs_rujukan/rs_api",
			success : function(data){
				var array_rs = data
				for (i = 0; i < array_rs.length; i++){
					var provinsi = array_rs[i].fields.provinsi
					var telepon = array_rs[i].fields.telepon
					if (provinsi.toLowerCase() == "{{ provinsi }}".toLowerCase() && telepon != '-'){
						$("#find").hide();
						nama_rs = array_rs[i].fields.nama;
						alamat = array_rs[i].fields.alamat;
						$("#answer").append(nama_rs + "<br><br>Alamat : " + alamat +  ", " + provinsi)
						$("#mytable_filter :input").val(nama_rs)
						$("#mytable_filter :input").keyup()
						$("#mytable_filter :input").val("")
						$("#call").show()
						var nomor = "tel:" + telepon
						$("#link").attr("href", nomor)
						break;
					}
				}
			}
		})
	})
</script>
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
<!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script> -->
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script> -->
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/responsive.bootstrap.min.js"></script>
{% endblock %}