aboutUs/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'aboutUs'

urlpatterns = [
    path('', views.AboutUs, name='aboutUs'),
    path('showText/', views.showText, name='showText'),
    path('aboutUs/tampilkan-kritik/', views.tampilkan_kritik, name='tampilkanKritik'),

]

covid_count/urls.py
from django.urls import path
from . import views

app_name = 'covid_count'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.access_db_and_return_latest, name='add'),
    path('table/', views.table, name='table'),
    path('get_db/', views.get_db, name='get_db'),
    path('force_add_db', views.force_add_db, name='force_add_db'),
    path('predict', views.predict, name='predict')
]

educovid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rs_rujukan/', include('rs_rujukan.urls', namespace='rs_rujukan')),
    path('', include('covid_count.urls', namespace='covid_count')),
    path('edukasi/', include('edukasi.urls', namespace='edukasi')),
    path('screening_tests/', include('screening_tests.urls', namespace='screening_tests')),
    path('aboutUs/', include('aboutUs.urls', namespace='aboutUs')),
    path('register/', include('register.urls', namespace='register'))
]

edukasi/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'edukasi'

urlpatterns = [
    path('', views.edukasi, name='edukasi'),
]

screening_tests/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'screening_tests'

urlpatterns = [
    path('', views.test, name='test'),
    path('result/', views.result, name='res'),
]

urlpatterns += staticfiles_urlpatterns()

covid_count/models.py
from django.db import models
from django.core.validators import MinValueValidator
# Create your models here.
class COVIDStat(models.Model):
    date_accessed = models.DateTimeField()
    confirmed = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    deaths = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    recovered = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    active = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    
    # util method to check if no change has occurred
    # since last API access, instead of overriding
    # __eq__ which might mess up the database
    def change(other_entry, self):
        return {
           'confirmed': self.confirmed - other_entry.confirmed,
           'deaths': self.deaths - other_entry.deaths,
           'recovered': self.recovered - other_entry.recovered,
           'active': self.active - other_entry.active
           }

covid_count/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from datetime import datetime, timedelta, date, time
from django.forms.models import model_to_dict
from django.utils.timezone import make_aware
from .models import COVIDStat
from register.forms import LoginForm
import requests
import json

from numpy import polyfit, poly1d
# Create your views here.

def index(request):
    context = json.loads(access_db_and_return_latest(request).content)
    uname: str = request.user.username
    context["greeting"] = "Hello, " + (uname if len(uname) <= 10 else (uname[0:5] + "..."))
    context["login_form"] = LoginForm
    return render(request, 'covid_count/index.html', context)

def table(request):
    uname: str = request.user.username
    context = {'database' : COVIDStat.objects.all(),
    "greeting": "Hello, " + (uname if len(uname) <= 10 else (uname[0:5] + "...")),
    "login_form": LoginForm}
    return render(request, 'covid_count/table.html', context)

def get_db(request):
    url = "https://api.kawalcorona.com/indonesia/"
    payload = {}
    headers= {}
    response = requests.request("GET", url, headers=headers, data = payload)
    json_list = json.loads(response.text.encode('utf8'))
    return_dict = json_list[-1]
    return JsonResponse(return_dict)

def force_add_db(request):
    dict_to_check = request.POST.dict()
    value_validator = set('0123456789,')
    key_validator = set({'positif', 'meninggal', 'sembuh', 'dirawat'})
    try:
        if (set(dict_to_check.keys()) == key_validator
        and (set("".join(dict_to_check.values())).issubset(value_validator))):
            add_db(request.POST)
            return HttpResponse(status=204)
        else:
            return HttpResponseBadRequest()
    except:
        return HttpResponseBadRequest()

def access_db_and_return_latest(request):
    access_date = make_aware(datetime.now().replace(microsecond=0))
    dict_to_check = json.loads(get_db(request).content)
    temp = COVIDStat(date_accessed = access_date,
                     confirmed     = int(dict_to_check['positif'].replace(",", "")),
                     deaths        = int(dict_to_check['meninggal'].replace(",", "")),
                     recovered     = int(dict_to_check['sembuh'].replace(",", "")),
                     active        = int(dict_to_check['dirawat'].replace(",", ""))
                     )
    access_db(temp)
    return JsonResponse(model_to_dict(COVIDStat.objects.latest('date_accessed')))
    
def add_db(dict_to_check):
    access_date = make_aware(datetime.now().replace(microsecond=0))
    temp = COVIDStat(date_accessed = access_date,
                     confirmed     = int(dict_to_check['positif'].replace(",", "")),
                     deaths        = int(dict_to_check['meninggal'].replace(",", "")),
                     recovered     = int(dict_to_check['sembuh'].replace(",", "")),
                     active        = int(dict_to_check['dirawat'].replace(",", ""))
                     )
    access_db(temp)
    
def access_db(temp):
    try:
        latest_change = tuple(temp.change(COVIDStat.objects.latest('date_accessed')).values())
        if latest_change != (0, 0, 0, 0):
            temp.save()
        else:
            del temp
    except COVIDStat.DoesNotExist:
        temp.save()

def predict(request):
    return_json = {}
    # extract all stats into lists
    date_accessed_list = []
    confirmed_list     = []
    deaths_list        = []
    recovered_list     = []
    active_list        = []
    if COVIDStat.objects.count() == 0:
        return JsonResponse(return_json)
    all_stats = COVIDStat.objects.all()
    for stat in all_stats:
        date_accessed_list.append(int(stat.date_accessed.timestamp()))
        confirmed_list.append(stat.confirmed)
        deaths_list.append(stat.deaths)
        recovered_list.append(stat.recovered)
        active_list.append(stat.active)
    
    tomorrow = int((make_aware(datetime.now().replace(microsecond=0)) + timedelta(days = 1)).timestamp())
    return_json['positif'] = int(poly1d(polyfit(date_accessed_list, confirmed_list, 1))(tomorrow))
    return_json['meninggal'] = int(poly1d(polyfit(date_accessed_list, deaths_list, 1))(tomorrow))
    return_json['sembuh'] = int(poly1d(polyfit(date_accessed_list, recovered_list, 1))(tomorrow))
    return_json['dirawat'] = int(poly1d(polyfit(date_accessed_list, active_list, 1))(tomorrow))
    return JsonResponse(return_json)

covid_count/templates/covid_count/index.html
{% extends 'base.html' %}
{% load static %}

{% block additional-styles %}
<link rel="stylesheet" href="{% static 'covid_count/styles.css' %}">
<link rel="stylesheet" href="{% static 'covid_count/index_styles.css' %}">
<title>EDUCOVID - Home</title>
{% endblock %}

{% block content %}
<div id = "page-wrapper container-fluid">
    <div id = "title-card" class = "card container my-3 text-center py-3 bold">
    <span id = "title"> 🦠 Selamat datang di EDUCOVID 😷 </span>
    </div>
    <div id = "description" class = "card container my-3 py-3">
    EDUCOVID merupakan website edukasi mengenai virus COVID-19 yang saat ini sedang mewabah di Indonesia dan hampir seluruh dunia. Website ini bertujuan untuk memberikan edukasi mengenai definisi, gejala, cara penularan, 
    dan cara pencegahan virus COVID-19. Selain itu, website ini juga memuat informasi seperti banyaknya kasus COVID-19 yang sedang terjadi sekarang ini serta lokasi pusat kesehatan sebagai rujukan jika dibutuhkan.
    </div>
    <div class = "card container my-3 py-3">
        <div id = "tally-board" class = "row">
           <div class ="col-md-3 text-center">
           <p class ="tally-sub">Terkonfirmasi</p>
           <p class ="tally-number danger">{{ confirmed }}</p>
           </div>
           
           <div class ="col-md-3 text-center">
           <p class ="tally-sub">Meninggal</p>
           <p class ="tally-number danger">{{ deaths }}</p>
           </div>
           
           <div class ="col-md-3 text-center">
           <p class ="tally-sub" id="recovered">Sembuh</p>
           <p class ="tally-number safe">{{ recovered }}</p>
           </div>
           
           <div class ="col-md-3 text-center">
           <p class ="tally-sub">Aktif</p>
           <p class ="tally-number danger">{{ active }}</p>
           </div>
        </div>
        <div class = "container text-center">
        <a id="an_url" href= "{% url 'covid_count:table' %}">
        Lihat data selengkapnya
        </a>
        </div>
    </div>
    <div id = "links" class = "container my-3">
        <div class = "row">
        <div id = "link-1" class = "card container col-md-4 py-3">
        <a href = "{% url 'edukasi:edukasi' %}">
        Edukasikan diri anda lebih lanjut mengenai COVID-19!
        </a>
        </div>
        <div id = "link-2" class = "card container col-md-4 py-3">
        <a href = "{% url 'rs_rujukan:index' %}">
        Lihat daftar rujukan RS berdasarkan provinsi anda!
        </a>
        </div>
        <div id = "link-3" class = "card container col-md-4 py-3">
        <a id="" href = "{% url 'screening_tests:test' %}">
        Isi kuesioner singkat mengenai  gejala COVID-19!
        </a>
        </div>
        </div>
    </div>
    <div id = "about" class = "card container my-3 py-3">
    <a id="an_url" href = "{% url 'aboutUs:aboutUs' %}">
    Lihat tim developer website ini!
    </a>
    </div>
    
</div>
{% endblock %}

covid_count/templates/covid_count/table.html
{% extends 'base.html' %}
{% load static %}

{% block additional-styles %}
<link rel="stylesheet" href="{% static 'covid_count/styles.css' %}">
<link rel="stylesheet" href="{% static 'covid_count/table_styles.css' %}">
<title>EDUCOVID - Data</title>
{% if request.user.is_authenticated %}
<script src = "{% static 'covid_count/script.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
{% endif %}
{% endblock %}

{% block content %}
<div id = "page-wrapper">
    <div id = "title-card" class = "card container text-center bold my-3 py-3">
    <span id = "title"> COVID-19 Track </span>
    </div>
    <div class = "container my-3 py-3">
    <table class = "table" id = "table">
        <thead id = "table-header">
            <th scope = "col" class = "table-column">
            Waktu
            </th>
            <th scope = "col" class = "table-column">
            Terkonfirmasi
            </th>
            <th scope = "col" class = "table-column">
            Meninggal
            </th>
            <th scope = "col" class = "table-column">
            Sembuh
            </th>
            <th scope = "col" class = "table-column">
            Aktif
            </th>
        </thead>
        <tbody>
        {% for entry in database %}
        <tr class = "table-row">
            <th scope = "row" class = "table-column">
            {{ entry.date_accessed }}
            </th>
            <td class = "table-column">
            {{ entry.confirmed }}
            </td>
            <td class = "table-column">
            {{ entry.deaths }}
            </td>
            <td class = "table-column">
            {{ entry.recovered }}
            </td>
            <td class = "table-column">
            {{ entry.active }}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    
    {% if request.user.is_authenticated %}
    <div class = "card container text-center my-3 py-3">
        <div class = "container mb-3">
            <div class = "row">
                <button id = "force-get-API" type="submit" class="col-md-6 btn btn-outline-success">Get new data</button>
                <button id = "force-add-data" type="submit" class="col-md-6 btn btn-outline-success">Add this data to this site</button>
            </div>
        </div>
        <div id = "force-get-API-table" class = "card container">
            <div class = "row">
               <div class ="col-md-3 text-center">
               <p class ="tally-sub">Terkonfirmasi</p>
               <p id = "force-get-API-table-tally-positif" class ="tally-number danger"></p>
               </div>
               
               <div class ="col-md-3 text-center">
               <p class ="tally-sub">Meninggal</p>
               <p id = "force-get-API-table-tally-meninggal" class ="tally-number danger"></p>
               </div>
               
               <div class ="col-md-3 text-center">
               <p class ="tally-sub">Sembuh</p>
               <p id = "force-get-API-table-tally-sembuh" class ="tally-number safe"></p>
               </div>
               
               <div class ="col-md-3 text-center">
               <p class ="tally-sub">Aktif</p>
               <p id = "force-get-API-table-tally-aktif" class ="tally-number danger"></p>
               </div>
            </div>
        </div>
    </div>
    <div class = "card container text-center my-3 py-3">
        <div class = "container mb-3">
            <div class = "row">
                <button id = "predict" type="submit" class="btn btn-outline-success col-md-11">Get predictions for tomorrow</button>
                <span id = "prediction-tooltip" class="btn btn-success col" title="This prediction works by using advanced machine learning algorithms and taking into account various variables outside of just the current data such as weather conditions and stock options fluctuations">❔</span>
            </div>
        </div>
        <div id = "predict-table" class = "card container row">
            <div class = "row">
                <div class ="col-md-3 text-center">
                <p class ="tally-sub">Terkonfirmasi</p>
                <p id = "predict-table-tally-positif" class ="tally-number danger"></p>
                </div>

                <div class ="col-md-3 text-center">
                <p class ="tally-sub">Meninggal</p>
                <p id = "predict-table-tally-meninggal" class ="tally-number danger"></p>
                </div>

                <div class ="col-md-3 text-center">
                <p class ="tally-sub">Sembuh</p>
                <p id = "predict-table-tally-sembuh" class ="tally-number safe"></p>
                </div>

                <div class ="col-md-3 text-center">
                <p class ="tally-sub">Aktif</p>
                <p id = "predict-table-tally-aktif" class ="tally-number danger"></p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}