aboutUs/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'aboutUs'

urlpatterns = [
    path('', views.AboutUs, name='aboutUs'),
    path('showText/', views.showText, name='showText'),
    path('aboutUs/tampilkan-kritik/', views.tampilkan_kritik, name='tampilkanKritik'),

]

educovid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rs_rujukan/', include('rs_rujukan.urls', namespace='rs_rujukan')),
    path('', include('covid_count.urls', namespace='covid_count')),
    path('edukasi/', include('edukasi.urls', namespace='edukasi')),
    path('screening_tests/', include('screening_tests.urls', namespace='screening_tests')),
    path('aboutUs/', include('aboutUs.urls', namespace='aboutUs')),
    path('register/', include('register.urls', namespace='register'))
]

edukasi/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'edukasi'

urlpatterns = [
    path('', views.edukasi, name='edukasi'),
]

register/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.signup, name='signup'),
    path('logon/', views.logon, name='logon'),
    path('logoff/', views.logoff, name='logoff'),
]

rs_rujukan/urls.py
from django.contrib import admin
from django.urls import path
from rs_rujukan import views

app_name = "rs_rujukan"

urlpatterns = [
   	path('', views.index, name='index'),
   	# path('data_rs/', views.data_rs, name='data_rs'),
   	path('rs_api/', views.rs_api, name='rs_api'),
   	path('add_rs/', views.add_rs, name='add_rs'),
]

screening_tests/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'screening_tests'

urlpatterns = [
    path('', views.test, name='test'),
    path('result/', views.result, name='res'),
]

urlpatterns += staticfiles_urlpatterns()

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">
     <link rel="icon" href="https://www.flaticon.com/svg/static/icons/svg/2813/2813238.svg" type="image/gif"> 
    {% block additional-styles %}
    {% endblock %}
</head>

<body>
    <div class="placeholder">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
            {% if not request.user.is_authenticated %}
                <div class="dropdown mr-3">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Login
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <form method="POST" action="{% url 'register:logon' %}" class="form px-4 py-3">
                            {% csrf_token %}
                            {% for field in login_form %}
                                <div class="form-group">
                                <label>{{ field.label }}</label>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn btn-outline-success">Login</button>
                        </form>
                        <a class="btn dropdown-item btn-outline-success" href="{% url 'register:signup' %}">No account? Register</a>
                    </div>
                </div>
            {% else %}
                <span class="navbar-text mr-3">{{ greeting }}</span>
                <a href="{% url 'register:logoff' %}" class="text-center mr-3">Log Off</a>
            {% endif %}
                <a class="navbar-brand" href="{% url 'covid_count:index' %}">
                    <img src="https://www.flaticon.com/svg/static/icons/svg/2813/2813238.svg">
                    <small class="font-weight-bold mb-0 text-uppercase">EDUCOVID</small>
                </a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'covid_count:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'edukasi:edukasi' %}">Edukasi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'rs_rujukan:index' %}">RS Rujukan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'screening_tests:test' %}">Uji Screening</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'aboutUs:aboutUs' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
        
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="page-footer font-small blue pt-4">
        <div class="container-fluid text-center text-md-center">
            EDUCOVID
        </div>
        <div class="footer-copyright text-center py-3">
            ©2020 Kelompok D11, All Rights Reserved
        </div>
    </footer>
</body>
</html>